# Generated by Django 3.2.5 on 2021-07-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstterm',
            options={'ordering': ('-created',), 'verbose_name': 'First Term Score', 'verbose_name_plural': 'First Term Scores'},
        ),
        migrations.RenameField(
            model_name='firstterm',
            old_name='literacy',
            new_name='cumulative',
        ),
        migrations.RemoveField(
            model_name='firstterm',
            name='general_studies',
        ),
        migrations.RemoveField(
            model_name='firstterm',
            name='numeracy',
        ),
        migrations.RemoveField(
            model_name='firstterm',
            name='science',
        ),
        migrations.AddField(
            model_name='firstterm',
            name='general_studies_ca1',
            field=models.IntegerField(blank=True, default=0, verbose_name='General Studies (1st CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='general_studies_ca2',
            field=models.IntegerField(blank=True, default=0, verbose_name='General Studies (2nd CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='general_studies_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='General Studies (EXAM)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='literacy_ca1',
            field=models.IntegerField(blank=True, default=0, verbose_name='Literacy (1st CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='literacy_ca2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Literacy (2nd CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='literacy_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='Literacy (EXAM)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='numeracy_ca1',
            field=models.IntegerField(blank=True, default=0, verbose_name='Numeracy (1st CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='numeracy_ca2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Numeracy (2nd CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='numeracy_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='Numeracy (EXAM)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='science_ca1',
            field=models.IntegerField(blank=True, default=0, verbose_name='Science and Health (1st CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='science_ca2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Science and Health (2nd CA)'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='science_exam',
            field=models.IntegerField(blank=True, default=0, verbose_name='Science and Health (EXAM)'),
        ),
    ]
