# Generated by Django 3.2.5 on 2021-07-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20210720_0159'),
        ('pre_basic', '0002_auto_20210720_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstterm',
            name='user',
        ),
        migrations.AddField(
            model_name='firstterm',
            name='pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.pupil'),
        ),
    ]
