# Generated by Django 3.2.5 on 2021-07-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20210720_0159'),
        ('pre_basic', '0004_firstterm_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstterm',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.class', verbose_name='Class'),
        ),
    ]
