# Generated by Django 3.2.5 on 2021-07-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('pre_basic', '0005_alter_firstterm_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.session'),
        ),
    ]
