# Generated by Django 3.2.5 on 2021-07-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0006_firstterm_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstterm',
            name='classe',
        ),
    ]
