# Generated by Django 3.2.5 on 2021-07-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('pre_basic', '0007_remove_firstterm_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstterm',
            name='session',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.session'),
        ),
    ]
