# Generated by Django 3.2.5 on 2021-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0008_alter_firstterm_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='general_studies_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='literacy_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='numeracy_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='science_tot',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
