# Generated by Django 3.2.5 on 2021-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0009_auto_20210721_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='number_present',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='No of Days Present'),
        ),
    ]
