# Generated by Django 3.2.5 on 2021-07-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0010_firstterm_number_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='comprehension',
            field=models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='concentration',
            field=models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='homework',
            field=models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True, verbose_name='Homework Completion'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='innovative',
            field=models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='interest',
            field=models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True, verbose_name='Interest in Learning'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='reading',
            field=models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='responsiveness',
            field=models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='spoken',
            field=models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True, verbose_name='Spoken English'),
        ),
        migrations.AddField(
            model_name='firstterm',
            name='writing',
            field=models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True),
        ),
    ]
