# Generated by Django 3.2.4 on 2021-07-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0012_secondterm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstterm',
            options={'ordering': ('pupil',), 'verbose_name': 'First Term Score', 'verbose_name_plural': 'First Term Scores'},
        ),
        migrations.AlterModelOptions(
            name='secondterm',
            options={'ordering': ('pupil',), 'verbose_name': 'Second Term Score', 'verbose_name_plural': 'Second Term Scores'},
        ),
    ]
