# Generated by Django 3.2.4 on 2021-07-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210722_2157'),
        ('records', '0009_auto_20210726_1120'),
        ('pre_basic', '0013_auto_20210726_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstterm',
            options={'ordering': ('pupil__user__username',), 'verbose_name': 'First Term Score', 'verbose_name_plural': 'First Term Scores'},
        ),
        migrations.AlterModelOptions(
            name='secondterm',
            options={'ordering': ('pupil__user__username',), 'verbose_name': 'Second Term Score', 'verbose_name_plural': 'Second Term Scores'},
        ),
        migrations.CreateModel(
            name='ThirdTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literacy_ca1', models.IntegerField(blank=True, default=0, verbose_name='Literacy (1st CA)')),
                ('numeracy_ca1', models.IntegerField(blank=True, default=0, verbose_name='Numeracy (1st CA)')),
                ('general_studies_ca1', models.IntegerField(blank=True, default=0, verbose_name='General Studies (1st CA)')),
                ('science_ca1', models.IntegerField(blank=True, default=0, verbose_name='Science and Health (1st CA)')),
                ('literacy_ca2', models.IntegerField(blank=True, default=0, verbose_name='Literacy (2nd CA)')),
                ('numeracy_ca2', models.IntegerField(blank=True, default=0, verbose_name='Numeracy (2nd CA)')),
                ('general_studies_ca2', models.IntegerField(blank=True, default=0, verbose_name='General Studies (2nd CA)')),
                ('science_ca2', models.IntegerField(blank=True, default=0, verbose_name='Science and Health (2nd CA)')),
                ('literacy_exam', models.IntegerField(blank=True, default=0, verbose_name='Literacy (EXAM)')),
                ('numeracy_exam', models.IntegerField(blank=True, default=0, verbose_name='Numeracy (EXAM)')),
                ('general_studies_exam', models.IntegerField(blank=True, default=0, verbose_name='General Studies (EXAM)')),
                ('science_exam', models.IntegerField(blank=True, default=0, verbose_name='Science and Health (EXAM)')),
                ('numeracy_tot', models.IntegerField(blank=True, default=0)),
                ('literacy_tot', models.IntegerField(blank=True, default=0)),
                ('general_studies_tot', models.IntegerField(blank=True, default=0)),
                ('science_tot', models.IntegerField(blank=True, default=0)),
                ('cumulative', models.IntegerField(blank=True, default=0)),
                ('number_present', models.CharField(blank=True, max_length=8, null=True, verbose_name='No of Days Present')),
                ('concentration', models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True)),
                ('responsiveness', models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True)),
                ('comprehension', models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True)),
                ('interest', models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True, verbose_name='Interest in Learning')),
                ('homework', models.CharField(choices=[('Most times', 'Most times'), ('Some times', 'Some times'), ('Rarely', 'Rarely'), ('Always', 'Always')], max_length=15, null=True, verbose_name='Homework Completion')),
                ('reading', models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True)),
                ('writing', models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True)),
                ('spoken', models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True, verbose_name='Spoken English')),
                ('innovative', models.CharField(choices=[('Capable and Competent', 'Capable and Competent'), ('Experiencing Some Difficulties', 'Experiencing Some Difficulties'), ('Experiencing Significant Difficulties', 'Experiencing Significant Difficulties')], max_length=45, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.pupil')),
                ('session', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.session')),
            ],
            options={
                'verbose_name': 'Third Term Score',
                'verbose_name_plural': 'Third Term Scores',
                'ordering': ('pupil__user__username',),
            },
        ),
    ]
