# Generated by Django 3.2.4 on 2021-07-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210722_2157'),
        ('records', '0009_auto_20210726_1120'),
        ('pre_basic', '0014_auto_20210726_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstterm',
            name='pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_basic_pupil', to='records.pupil'),
        ),
        migrations.AlterField(
            model_name='firstterm',
            name='session',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_basic_session', to='management.session'),
        ),
    ]
