# Generated by Django 3.2.4 on 2021-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0015_auto_20210726_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdterm',
            name='all_cumulative',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
