# Generated by Django 3.2.4 on 2021-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0016_thirdterm_all_cumulative'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdterm',
            name='cumulative_1st',
            field=models.IntegerField(blank=True, default=0, verbose_name='1st Cumulative'),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='cumulative_2nd',
            field=models.IntegerField(blank=True, default=0, verbose_name='2nd Cumulative'),
        ),
    ]
