# Generated by Django 3.2.4 on 2021-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0017_auto_20210727_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdterm',
            name='cumulative_1st',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='1st Cumulative'),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='cumulative_2nd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='2nd Cumulative'),
        ),
    ]
