# Generated by Django 3.2.4 on 2021-07-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0018_auto_20210727_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdterm',
            name='general_studies_tot2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='general_studies_tot3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='literacy_tot2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='literacy_tot3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='numeracy_tot2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='numeracy_tot3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='science_tot2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='science_tot3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
