# Generated by Django 3.2.4 on 2021-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0019_auto_20210727_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdterm',
            old_name='general_studies_tot3',
            new_name='general_studies_cum',
        ),
        migrations.RenameField(
            model_name='thirdterm',
            old_name='literacy_tot3',
            new_name='general_studies_tot1',
        ),
        migrations.RenameField(
            model_name='thirdterm',
            old_name='numeracy_tot3',
            new_name='literacy_cum',
        ),
        migrations.RenameField(
            model_name='thirdterm',
            old_name='science_tot3',
            new_name='literacy_tot1',
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='numeracy_cum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='numeracy_tot1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='science_cum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='science_tot1',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
