# Generated by Django 3.2.4 on 2021-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0020_auto_20210727_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdterm',
            name='literacy_tot1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
