# Generated by Django 3.2.4 on 2021-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0021_alter_thirdterm_literacy_tot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdterm',
            name='cum_perc',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
