# Generated by Django 3.2.4 on 2021-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0022_thirdterm_cum_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdterm',
            name='general_studies_tot1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='general_studies_tot2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='literacy_tot2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='numeracy_tot1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='numeracy_tot2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='science_tot1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thirdterm',
            name='science_tot2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
