# Generated by Django 3.2.5 on 2021-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_basic', '0023_auto_20210727_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstterm',
            name='school_fees',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='secondterm',
            name='school_fees',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='thirdterm',
            name='school_fees',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
