# Generated by Django 3.2.5 on 2021-09-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_category_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='category',
        ),
    ]
