# Generated by Django 3.2.5 on 2021-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], default='Student', max_length=20, null=True),
        ),
    ]
