# Generated by Django 3.2.5 on 2021-09-08 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='pupil_img/%Y/%m/%d', verbose_name="Student's Photograph"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Staff',
                'ordering': ('member',),
            },
        ),
    ]
