# Generated by Django 3.2.5 on 2021-09-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210908_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='referrer',
        ),
    ]
