# Generated by Django 3.2.5 on 2021-09-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_person_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='pupil_img/%Y/%m/%d'),
        ),
    ]
