# Generated by Django 3.2.5 on 2021-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_person_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('A---n', 'A---n')], default='Student', max_length=20, null=True),
        ),
    ]
