# Generated by Django 3.2.5 on 2021-09-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Class(es) and Subject(s) I teach'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
