# Generated by Django 3.2.5 on 2021-09-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210920_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.RemoveField(
            model_name='webadmin',
            name='web_admin',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='WebAdmin',
        ),
    ]
