# Generated by Django 3.2.4 on 2022-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Admission Number/Username'),
        ),
    ]
