# Generated by Django 3.2.5 on 2021-09-08 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signature_img/%Y/%m/%d', verbose_name="Class Teacher's Signature")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('head', models.CharField(blank=True, max_length=40, null=True, verbose_name="Head of School's Name")),
                ('school', models.ImageField(blank=True, null=True, upload_to='stamp_img/%Y/%m/%d', verbose_name="School's Stamp with Head of Schools Signature")),
                ('number', models.CharField(blank=True, max_length=7, null=True, verbose_name='No of Days School Opens')),
                ('next', models.DateField(blank=True, null=True, verbose_name='Next Term Begins')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=2, null=True, verbose_name='S/N')),
                ('subject', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.class', verbose_name='Class')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('subject',),
            },
        ),
    ]
