# Generated by Django 3.2.5 on 2021-09-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('classe',), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='classe',
            field=models.CharField(max_length=20, null=True, verbose_name='Class'),
        ),
    ]
