# Generated by Django 3.2.5 on 2021-09-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210908_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-subject',)},
        ),
    ]
