# Generated by Django 3.2.5 on 2021-09-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_subject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('subject',)},
        ),
    ]
