# Generated by Django 3.2.5 on 2021-09-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='first_report',
            field=models.BooleanField(default=False, max_length=5, verbose_name='1st Term Report'),
        ),
        migrations.AddField(
            model_name='session',
            name='second_report',
            field=models.BooleanField(default=False, max_length=5, verbose_name='2nd Term Report'),
        ),
        migrations.AddField(
            model_name='session',
            name='third_report',
            field=models.BooleanField(default=False, max_length=5, verbose_name='3rd Term Report'),
        ),
    ]
