# Generated by Django 3.2.5 on 2021-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210915_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='first_report',
            field=models.BooleanField(default=False, max_length=5, verbose_name='Open 1st Term Report'),
        ),
        migrations.AlterField(
            model_name='session',
            name='school',
            field=models.ImageField(blank=True, null=True, upload_to='stamp_img/%Y/%m/%d', verbose_name="School's Stamp"),
        ),
        migrations.AlterField(
            model_name='session',
            name='second_report',
            field=models.BooleanField(default=False, max_length=5, verbose_name='Open 2nd Term Report'),
        ),
        migrations.AlterField(
            model_name='session',
            name='third_report',
            field=models.BooleanField(default=False, max_length=5, verbose_name='Open 3rd Term Report'),
        ),
    ]
