# Generated by Django 3.2.5 on 2021-09-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210917_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-created',)},
        ),
    ]
