# Generated by Django 3.2.5 on 2021-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_subject_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='head',
            new_name='first_head',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='next',
            new_name='first_next',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='number',
            new_name='first_number',
        ),
        migrations.AddField(
            model_name='session',
            name='second_head',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Head of School's Name"),
        ),
        migrations.AddField(
            model_name='session',
            name='second_next',
            field=models.DateField(blank=True, null=True, verbose_name='Next Term Begins'),
        ),
        migrations.AddField(
            model_name='session',
            name='second_number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='No of Days School Opens'),
        ),
        migrations.AddField(
            model_name='session',
            name='third_head',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Head of School's Name"),
        ),
        migrations.AddField(
            model_name='session',
            name='third_next',
            field=models.DateField(blank=True, null=True, verbose_name='Next Term Begins'),
        ),
        migrations.AddField(
            model_name='session',
            name='third_number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='No of Days School Opens'),
        ),
    ]
