# Generated by Django 3.2.4 on 2021-12-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0008_auto_20210928_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='first_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_first_head', to=settings.AUTH_USER_MODEL, verbose_name="Head of School's Name"),
        ),
        migrations.AlterField(
            model_name='session',
            name='second_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_second_head', to=settings.AUTH_USER_MODEL, verbose_name="Head of School's Name"),
        ),
        migrations.AlterField(
            model_name='session',
            name='third_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_third_head', to=settings.AUTH_USER_MODEL, verbose_name="Head of School's Name"),
        ),
    ]
