# Generated by Django 3.2.4 on 2022-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20211213_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classe',
            field=models.CharField(max_length=50, null=True, verbose_name='Class'),
        ),
    ]
