# Generated by Django 3.2.4 on 2022-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_class_classe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('-created',), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='classe',
            field=models.CharField(max_length=20, null=True, verbose_name='Class'),
        ),
    ]
