# Generated by Django 3.2.5 on 2021-09-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
