# Generated by Django 3.2.5 on 2021-09-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='home_page',
            field=models.BooleanField(default=False, max_length=5, verbose_name='Home Page'),
        ),
    ]
