# Generated by Django 3.2.5 on 2021-07-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_video'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='video',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
