# Generated by Django 3.2.5 on 2021-08-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ('-created',), 'verbose_name': 'Background Nasheed', 'verbose_name_plural': 'Background Nasheeds'},
        ),
    ]
