# Generated by Django 3.2.5 on 2021-09-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_background_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
