# Generated by Django 3.2.5 on 2021-07-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210720_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('-created',), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
