# Generated by Django 3.2.5 on 2021-07-20 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0003_auto_20210720_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='role',
            field=models.CharField(choices=[('Pupil', 'Pupil'), ('Student', 'Student'), ('Staff', 'Staff')], default='Pupil', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(choices=[('Pupil', 'Pupil'), ('Student', 'Student'), ('Staff', 'Staff')], default='Pupil', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.class', verbose_name='Class')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
