# Generated by Django 3.2.5 on 2021-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20210721_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature_img/%Y/%m/%d', verbose_name="Class Teacher's Signature"),
        ),
    ]
