# Generated by Django 3.2.5 on 2021-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_class_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='pupil_img/%Y/%m/%d', verbose_name="Pupil's Photograph"),
        ),
        migrations.AddField(
            model_name='student',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='pupil_img/%Y/%m/%d', verbose_name="Pupil's Photograph"),
        ),
    ]
