# Generated by Django 3.2.4 on 2021-07-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20210723_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('name',), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user',)},
        ),
    ]
