# Generated by Django 3.2.4 on 2021-07-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20210726_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'ordering': ('user__username',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user__username',)},
        ),
    ]
