# Generated by Django 3.2.4 on 2021-07-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20210726_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='school_fees',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='school_fees',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
