# Generated by Django 3.2.6 on 2021-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20210727_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='school_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_fees',
        ),
        migrations.AlterField(
            model_name='pupil',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='student_img/%Y/%m/%d', verbose_name="Student's Photograph"),
        ),
    ]
